@echo off
echo Starting Tours and Travel Backend...
cd backend
echo Installing dependencies...
call mvnw.cmd clean install -DskipTests
echo Starting Spring Boot application...
call mvnw.cmd spring-boot:run
pause